### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by ruhman**
Compatibility with Python 3

### CODE REVIEW

**Comment by keradus** [comment]
:+1:

**Comment by masellfoodpanda** [comment]
:+1:

**Comment by lightstrike** [comment]
👍 Believe this will also fix #59, at least for Python 3.5

**Comment by keradus** [comment]
ping @slimkrazy

**Comment by slimkrazy** [comment]
I've a day off work today - I'll be merging in a whole load of fixes, including this!

**Comment by keradus** [comment]
great to hear @slimkrazy !
Please, could you release new version after that? It would be great !

**Pull request merged**
